steps:

- name: 'golang'
  args: ['get', 'github.com/gruntwork-io/terratest/modules/gcp']

- name: 'golang'
  args: ['go', 'get', 'github.com/gruntwork-io/terratest/modules/terraform']

- name: 'golang'
  args: ['go', 'mod', 'init', 'terraunittest']
  dir: 'test/unit'

- name: 'golang'
  args: ['go', 'mod', 'tidy']
  dir: 'test/unit'

- name: 'golang'
  args: ['go', 'test', '-v', './...', '-timeout', '30m']
  dir: 'test/unit'