steps:

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'config', 'set', 'project', 'kc-gke-wp']

- name: 'golang'
  args: ['go','get', 'github.com/gruntwork-io/terratest/modules/gcp']

- name: 'golang'
  args: ['go', 'get', 'github.com/gruntwork-io/terratest/modules/terraform']

- name: 'golang'
  args: ['go', 'mod', 'init', 'terraunittest']
  dir: 'tests/unit'

- name: 'golang'
  args: ['go', 'mod', 'tidy']
  dir: 'tests/unit'

- name: 'golang'
  args: ['go', 'test', '-v', './...', '-timeout', '30m']
  dir: 'tests/unit'