steps:

- name: 'golang'
  args: ['go','get', 'github.com/gruntwork-io/terratest/modules/gcp']

- name: 'golang'
  args: ['go', 'get', 'github.com/gruntwork-io/terratest/modules/terraform']

- name: 'golang'
  args: ['go', 'mod', 'init', 'terraunittest']
  dir: 'tests/unit'

- name: 'golang'
  args: ['go', 'mod', 'tidy']
  dir: 'tests/unit'

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'test', '-v', './$MOD_NAME', '-timeout', '120m', '-p', '1']
  dir: 'tests/unit'
  env: ['GCLOUD_PROJECT=kc-gke-wp']

timeout: 7200s