steps:
- name: 'debian'
  args: ['cd', 'tests/unit']

- name: 'go'
  args: ['get', 'github.com/gruntwork-io/terratest/modules/gcp']

- name: 'go'
  args: ['mod', 'init', 'terraunittest']

- name: 'go'
  args: ['mod', 'tidy']

- name: 'go'
  args: ['test', '-v', './...', '-timeout', '30m']