steps:

- name: 'go'
  args: ['get', 'github.com/gruntwork-io/terratest/modules/gcp']

- name: 'go'
  args: ['get', 'github.com/gruntwork-io/terratest/modules/terraform']

- name: 'go'
  args: ['mod', 'init', 'terraunittest']
  dir: 'test/unit'

- name: 'go'
  args: ['mod', 'tidy']
  dir: 'test/unit'

- name: 'go'
  args: ['test', '-v', './...', '-timeout', '30m']
  dir: 'test/unit'