steps:
- id: 'tf init'
  name: 'hashicorp/terraform:0.12.24'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'terraform init'

- id: 'tf apply'
  name: 'hashicorp/terraform:0.12.24'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'terraform apply -auto-approve'