steps:

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'mod', 'init', 'terraunittest']
  dir: 'tests/unit'

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'mod', 'tidy']
  dir: 'tests/unit'

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'test', '-v', './...', '-timeout', '120m', '-p', '1']
  dir: 'tests/unit'
  env: ['GCLOUD_PROJECT=kc-gke-wp']

timeout: 7200s