steps:

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'mod', 'init', 'terraunittest']
  dir: 'tests/integration'

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'mod', 'tidy']
  dir: 'tests/integration'

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'test', '-v', '-timeout', '30m']
  dir: 'tests/integration'
  env: ['GCLOUD_PROJECT=kc-gke-wp']

timeout: 1800s